name: Deploy to GitHub Pages

on:
  push:
    branches: [feature/deploySetting]
  pull_request:
    branches: [feature/deploySetting]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.13.0] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: |
          git config --global user.name "github-actions[bot]" 
          git config --global user.email "github-actions[bot]@users.noreply.github.com" 
          git remote set-url origin https://${{ secrets.DEPLOY_SECRET }}@github.com/${{ github.repository }}
          npm run deploy
        env:
          DEPLOY_SECRET: ${{ secrets.DEPLOY_SECRET }} 