name: Deploy to GitHub pages

on:
  push:
    branches: [feature/deploySetting]
  pull_request:
    branches: [feature/deploySetting]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write 
      pages: write    
      id-token: write 

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Create 404.html for SPA routing
        run: cp build/index.html build/404.html

      - name: Deploy

        run: npm run deploy
        env:
          
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}